/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as StaffsIndexRouteImport } from './routes/staffs/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId'
import { Route as StaffsStaffIdRouteImport } from './routes/staffs/$staffId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffsIndexRoute = StaffsIndexRouteImport.update({
  id: '/staffs/',
  path: '/staffs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffsStaffIdRoute = StaffsStaffIdRouteImport.update({
  id: '/staffs/$staffId',
  path: '/staffs/$staffId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/staffs/$staffId': typeof StaffsStaffIdRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/staffs/': typeof StaffsIndexRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/staffs/$staffId': typeof StaffsStaffIdRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/customers': typeof CustomersIndexRoute
  '/staffs': typeof StaffsIndexRoute
  '/stores': typeof StoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/staffs/$staffId': typeof StaffsStaffIdRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/staffs/': typeof StaffsIndexRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers/$customerId'
    | '/staffs/$staffId'
    | '/stores/$storeId'
    | '/customers/'
    | '/staffs/'
    | '/stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers/$customerId'
    | '/staffs/$staffId'
    | '/stores/$storeId'
    | '/customers'
    | '/staffs'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/customers/$customerId'
    | '/staffs/$staffId'
    | '/stores/$storeId'
    | '/customers/'
    | '/staffs/'
    | '/stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  StaffsStaffIdRoute: typeof StaffsStaffIdRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  StaffsIndexRoute: typeof StaffsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staffs/': {
      id: '/staffs/'
      path: '/staffs'
      fullPath: '/staffs/'
      preLoaderRoute: typeof StaffsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staffs/$staffId': {
      id: '/staffs/$staffId'
      path: '/staffs/$staffId'
      fullPath: '/staffs/$staffId'
      preLoaderRoute: typeof StaffsStaffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  StaffsStaffIdRoute: StaffsStaffIdRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  StaffsIndexRoute: StaffsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
